/**
 * generated by Xtext 2.12.0
 */
package tablesaw.xtext.ui.labeling;

import org.eclipse.xtext.xbase.ui.labeling.XbaseDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class XawDescriptionLabelProvider extends XbaseDescriptionLabelProvider {
}
