/*
 * generated by Xtext 2.14.0
 */
package tablesaw.xtext.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractXawScopeProvider extends XbaseBatchScopeProvider {
}
