/*
 * generated by Xtext 2.14.0
 */
package tablesaw.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import tablesaw.xtext.parser.antlr.internal.InternalXawParser;
import tablesaw.xtext.services.XawGrammarAccess;

public class XawParser extends AbstractAntlrParser {

	@Inject
	private XawGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalXawParser createParser(XtextTokenStream stream) {
		return new InternalXawParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Xaw";
	}

	public XawGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(XawGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
