/**
 * generated by Xtext 2.12.0
 */
package tablesaw.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import tablesaw.xtext.XawRuntimeModule;
import tablesaw.xtext.XawStandaloneSetup;
import tablesaw.xtext.ide.XawIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class XawIdeSetup extends XawStandaloneSetup {
  @Override
  public Injector createInjector() {
    XawRuntimeModule _xawRuntimeModule = new XawRuntimeModule();
    XawIdeModule _xawIdeModule = new XawIdeModule();
    return Guice.createInjector(Modules2.mixin(_xawRuntimeModule, _xawIdeModule));
  }
}
