/**
 * generated by Xtext 2.12.0
 */
package tablesaw.xtext.ide;

import tablesaw.xtext.ide.AbstractXawIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class XawIdeModule extends AbstractXawIdeModule {
}
