/**
 * generated by Xtext 2.12.0
 */
package tablesaw.xtext;

import org.eclipse.xtext.xbase.compiler.XbaseCompiler;
import org.eclipse.xtext.xbase.interpreter.IExpressionInterpreter;
import org.eclipse.xtext.xbase.scoping.batch.ImplicitlyImportedFeatures;
import org.eclipse.xtext.xbase.scoping.featurecalls.OperatorMapping;
import org.eclipse.xtext.xbase.typesystem.computation.ITypeComputer;
import tablesaw.xtext.AbstractXawRuntimeModule;
import tablesaw.xtext.extensions.ImplicitlyImportedTypes;
import tablesaw.xtext.jvmmodel.XawCompiler;
import tablesaw.xtext.jvmmodel.XawInterpreter;
import tablesaw.xtext.jvmmodel.XawTypeComputer;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class XawRuntimeModule extends AbstractXawRuntimeModule {
  public Class<? extends ImplicitlyImportedFeatures> bindImplicitlyImportedFeatures() {
    return ImplicitlyImportedTypes.class;
  }
  
  public Class<? extends OperatorMapping> bindOperatorMapping() {
    return tablesaw.xtext.extensions.OperatorMapping.class;
  }
  
  public Class<? extends ITypeComputer> bindITypeComputer() {
    return XawTypeComputer.class;
  }
  
  public Class<? extends XbaseCompiler> bindXbaseCompiler() {
    return XawCompiler.class;
  }
  
  @Override
  public Class<? extends IExpressionInterpreter> bindIExpressionInterpreter() {
    return XawInterpreter.class;
  }
}
