/**
 * generated by Xtext 2.14.0
 */
package tablesaw.xtext.xaw;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see tablesaw.xtext.xaw.XawPackage
 * @generated
 */
public interface XawFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  XawFactory eINSTANCE = tablesaw.xtext.xaw.impl.XawFactoryImpl.init();

  /**
   * Returns a new object of class '<em>XMethod</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>XMethod</em>'.
   * @generated
   */
  XMethod createXMethod();

  /**
   * Returns a new object of class '<em>Xaw</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Xaw</em>'.
   * @generated
   */
  Xaw createXaw();

  /**
   * Returns a new object of class '<em>Table Literal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Table Literal</em>'.
   * @generated
   */
  TableLiteral createTableLiteral();

  /**
   * Returns a new object of class '<em>Table Column</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Table Column</em>'.
   * @generated
   */
  TableColumn createTableColumn();

  /**
   * Returns a new object of class '<em>Inline Table Row</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Inline Table Row</em>'.
   * @generated
   */
  InlineTableRow createInlineTableRow();

  /**
   * Returns a new object of class '<em>Table Row Literal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Table Row Literal</em>'.
   * @generated
   */
  TableRowLiteral createTableRowLiteral();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  XawPackage getXawPackage();

} //XawFactory
