/**
 * generated by Xtext 2.14.0
 */
package tablesaw.xtext.xaw;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.xtext.xbase.XbasePackage;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see tablesaw.xtext.xaw.XawFactory
 * @model kind="package"
 * @generated
 */
public interface XawPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "xaw";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "tablesaw/xtext/Xaw";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "xaw";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  XawPackage eINSTANCE = tablesaw.xtext.xaw.impl.XawPackageImpl.init();

  /**
   * The meta object id for the '{@link tablesaw.xtext.xaw.impl.XMethodImpl <em>XMethod</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see tablesaw.xtext.xaw.impl.XMethodImpl
   * @see tablesaw.xtext.xaw.impl.XawPackageImpl#getXMethod()
   * @generated
   */
  int XMETHOD = 0;

  /**
   * The feature id for the '<em><b>Return Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XMETHOD__RETURN_TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XMETHOD__NAME = 1;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XMETHOD__PARAMETERS = 2;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XMETHOD__BODY = 3;

  /**
   * The number of structural features of the '<em>XMethod</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XMETHOD_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link tablesaw.xtext.xaw.impl.XawImpl <em>Xaw</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see tablesaw.xtext.xaw.impl.XawImpl
   * @see tablesaw.xtext.xaw.impl.XawPackageImpl#getXaw()
   * @generated
   */
  int XAW = 1;

  /**
   * The feature id for the '<em><b>Expressions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int XAW__EXPRESSIONS = XbasePackage.XBLOCK_EXPRESSION__EXPRESSIONS;

  /**
   * The feature id for the '<em><b>Import Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XAW__IMPORT_SECTION = XbasePackage.XBLOCK_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>QName</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XAW__QNAME = XbasePackage.XBLOCK_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Methods</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XAW__METHODS = XbasePackage.XBLOCK_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Xaw</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XAW_FEATURE_COUNT = XbasePackage.XBLOCK_EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link tablesaw.xtext.xaw.impl.TableLiteralImpl <em>Table Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see tablesaw.xtext.xaw.impl.TableLiteralImpl
   * @see tablesaw.xtext.xaw.impl.XawPackageImpl#getTableLiteral()
   * @generated
   */
  int TABLE_LITERAL = 2;

  /**
   * The feature id for the '<em><b>Expressions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int TABLE_LITERAL__EXPRESSIONS = XbasePackage.XBLOCK_EXPRESSION__EXPRESSIONS;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_LITERAL__NAME = XbasePackage.XBLOCK_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Table Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_LITERAL_FEATURE_COUNT = XbasePackage.XBLOCK_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link tablesaw.xtext.xaw.impl.TableColumnImpl <em>Table Column</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see tablesaw.xtext.xaw.impl.TableColumnImpl
   * @see tablesaw.xtext.xaw.impl.XawPackageImpl#getTableColumn()
   * @generated
   */
  int TABLE_COLUMN = 3;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_COLUMN__TYPE = XbasePackage.XEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_COLUMN__NAME = XbasePackage.XEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_COLUMN__EXPRESSION = XbasePackage.XEXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Table Column</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_COLUMN_FEATURE_COUNT = XbasePackage.XEXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link tablesaw.xtext.xaw.impl.InlineTableRowImpl <em>Inline Table Row</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see tablesaw.xtext.xaw.impl.InlineTableRowImpl
   * @see tablesaw.xtext.xaw.impl.XawPackageImpl#getInlineTableRow()
   * @generated
   */
  int INLINE_TABLE_ROW = 4;

  /**
   * The feature id for the '<em><b>Expressions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int INLINE_TABLE_ROW__EXPRESSIONS = XbasePackage.XBLOCK_EXPRESSION__EXPRESSIONS;

  /**
   * The number of structural features of the '<em>Inline Table Row</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INLINE_TABLE_ROW_FEATURE_COUNT = XbasePackage.XBLOCK_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link tablesaw.xtext.xaw.impl.TableRowLiteralImpl <em>Table Row Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see tablesaw.xtext.xaw.impl.TableRowLiteralImpl
   * @see tablesaw.xtext.xaw.impl.XawPackageImpl#getTableRowLiteral()
   * @generated
   */
  int TABLE_ROW_LITERAL = 5;

  /**
   * The feature id for the '<em><b>Expressions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_ROW_LITERAL__EXPRESSIONS = XbasePackage.XEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Table Row Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_ROW_LITERAL_FEATURE_COUNT = XbasePackage.XEXPRESSION_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link tablesaw.xtext.xaw.XMethod <em>XMethod</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XMethod</em>'.
   * @see tablesaw.xtext.xaw.XMethod
   * @generated
   */
  EClass getXMethod();

  /**
   * Returns the meta object for the containment reference '{@link tablesaw.xtext.xaw.XMethod#getReturnType <em>Return Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Return Type</em>'.
   * @see tablesaw.xtext.xaw.XMethod#getReturnType()
   * @see #getXMethod()
   * @generated
   */
  EReference getXMethod_ReturnType();

  /**
   * Returns the meta object for the attribute '{@link tablesaw.xtext.xaw.XMethod#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see tablesaw.xtext.xaw.XMethod#getName()
   * @see #getXMethod()
   * @generated
   */
  EAttribute getXMethod_Name();

  /**
   * Returns the meta object for the containment reference list '{@link tablesaw.xtext.xaw.XMethod#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see tablesaw.xtext.xaw.XMethod#getParameters()
   * @see #getXMethod()
   * @generated
   */
  EReference getXMethod_Parameters();

  /**
   * Returns the meta object for the containment reference '{@link tablesaw.xtext.xaw.XMethod#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see tablesaw.xtext.xaw.XMethod#getBody()
   * @see #getXMethod()
   * @generated
   */
  EReference getXMethod_Body();

  /**
   * Returns the meta object for class '{@link tablesaw.xtext.xaw.Xaw <em>Xaw</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Xaw</em>'.
   * @see tablesaw.xtext.xaw.Xaw
   * @generated
   */
  EClass getXaw();

  /**
   * Returns the meta object for the containment reference '{@link tablesaw.xtext.xaw.Xaw#getImportSection <em>Import Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Import Section</em>'.
   * @see tablesaw.xtext.xaw.Xaw#getImportSection()
   * @see #getXaw()
   * @generated
   */
  EReference getXaw_ImportSection();

  /**
   * Returns the meta object for the attribute '{@link tablesaw.xtext.xaw.Xaw#getQName <em>QName</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>QName</em>'.
   * @see tablesaw.xtext.xaw.Xaw#getQName()
   * @see #getXaw()
   * @generated
   */
  EAttribute getXaw_QName();

  /**
   * Returns the meta object for the containment reference list '{@link tablesaw.xtext.xaw.Xaw#getMethods <em>Methods</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Methods</em>'.
   * @see tablesaw.xtext.xaw.Xaw#getMethods()
   * @see #getXaw()
   * @generated
   */
  EReference getXaw_Methods();

  /**
   * Returns the meta object for class '{@link tablesaw.xtext.xaw.TableLiteral <em>Table Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table Literal</em>'.
   * @see tablesaw.xtext.xaw.TableLiteral
   * @generated
   */
  EClass getTableLiteral();

  /**
   * Returns the meta object for the attribute '{@link tablesaw.xtext.xaw.TableLiteral#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see tablesaw.xtext.xaw.TableLiteral#getName()
   * @see #getTableLiteral()
   * @generated
   */
  EAttribute getTableLiteral_Name();

  /**
   * Returns the meta object for class '{@link tablesaw.xtext.xaw.TableColumn <em>Table Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table Column</em>'.
   * @see tablesaw.xtext.xaw.TableColumn
   * @generated
   */
  EClass getTableColumn();

  /**
   * Returns the meta object for the containment reference '{@link tablesaw.xtext.xaw.TableColumn#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see tablesaw.xtext.xaw.TableColumn#getType()
   * @see #getTableColumn()
   * @generated
   */
  EReference getTableColumn_Type();

  /**
   * Returns the meta object for the attribute '{@link tablesaw.xtext.xaw.TableColumn#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see tablesaw.xtext.xaw.TableColumn#getName()
   * @see #getTableColumn()
   * @generated
   */
  EAttribute getTableColumn_Name();

  /**
   * Returns the meta object for the containment reference '{@link tablesaw.xtext.xaw.TableColumn#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see tablesaw.xtext.xaw.TableColumn#getExpression()
   * @see #getTableColumn()
   * @generated
   */
  EReference getTableColumn_Expression();

  /**
   * Returns the meta object for class '{@link tablesaw.xtext.xaw.InlineTableRow <em>Inline Table Row</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Inline Table Row</em>'.
   * @see tablesaw.xtext.xaw.InlineTableRow
   * @generated
   */
  EClass getInlineTableRow();

  /**
   * Returns the meta object for class '{@link tablesaw.xtext.xaw.TableRowLiteral <em>Table Row Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table Row Literal</em>'.
   * @see tablesaw.xtext.xaw.TableRowLiteral
   * @generated
   */
  EClass getTableRowLiteral();

  /**
   * Returns the meta object for the containment reference list '{@link tablesaw.xtext.xaw.TableRowLiteral#getExpressions <em>Expressions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expressions</em>'.
   * @see tablesaw.xtext.xaw.TableRowLiteral#getExpressions()
   * @see #getTableRowLiteral()
   * @generated
   */
  EReference getTableRowLiteral_Expressions();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  XawFactory getXawFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link tablesaw.xtext.xaw.impl.XMethodImpl <em>XMethod</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see tablesaw.xtext.xaw.impl.XMethodImpl
     * @see tablesaw.xtext.xaw.impl.XawPackageImpl#getXMethod()
     * @generated
     */
    EClass XMETHOD = eINSTANCE.getXMethod();

    /**
     * The meta object literal for the '<em><b>Return Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XMETHOD__RETURN_TYPE = eINSTANCE.getXMethod_ReturnType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XMETHOD__NAME = eINSTANCE.getXMethod_Name();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XMETHOD__PARAMETERS = eINSTANCE.getXMethod_Parameters();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XMETHOD__BODY = eINSTANCE.getXMethod_Body();

    /**
     * The meta object literal for the '{@link tablesaw.xtext.xaw.impl.XawImpl <em>Xaw</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see tablesaw.xtext.xaw.impl.XawImpl
     * @see tablesaw.xtext.xaw.impl.XawPackageImpl#getXaw()
     * @generated
     */
    EClass XAW = eINSTANCE.getXaw();

    /**
     * The meta object literal for the '<em><b>Import Section</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XAW__IMPORT_SECTION = eINSTANCE.getXaw_ImportSection();

    /**
     * The meta object literal for the '<em><b>QName</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XAW__QNAME = eINSTANCE.getXaw_QName();

    /**
     * The meta object literal for the '<em><b>Methods</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XAW__METHODS = eINSTANCE.getXaw_Methods();

    /**
     * The meta object literal for the '{@link tablesaw.xtext.xaw.impl.TableLiteralImpl <em>Table Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see tablesaw.xtext.xaw.impl.TableLiteralImpl
     * @see tablesaw.xtext.xaw.impl.XawPackageImpl#getTableLiteral()
     * @generated
     */
    EClass TABLE_LITERAL = eINSTANCE.getTableLiteral();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TABLE_LITERAL__NAME = eINSTANCE.getTableLiteral_Name();

    /**
     * The meta object literal for the '{@link tablesaw.xtext.xaw.impl.TableColumnImpl <em>Table Column</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see tablesaw.xtext.xaw.impl.TableColumnImpl
     * @see tablesaw.xtext.xaw.impl.XawPackageImpl#getTableColumn()
     * @generated
     */
    EClass TABLE_COLUMN = eINSTANCE.getTableColumn();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE_COLUMN__TYPE = eINSTANCE.getTableColumn_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TABLE_COLUMN__NAME = eINSTANCE.getTableColumn_Name();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE_COLUMN__EXPRESSION = eINSTANCE.getTableColumn_Expression();

    /**
     * The meta object literal for the '{@link tablesaw.xtext.xaw.impl.InlineTableRowImpl <em>Inline Table Row</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see tablesaw.xtext.xaw.impl.InlineTableRowImpl
     * @see tablesaw.xtext.xaw.impl.XawPackageImpl#getInlineTableRow()
     * @generated
     */
    EClass INLINE_TABLE_ROW = eINSTANCE.getInlineTableRow();

    /**
     * The meta object literal for the '{@link tablesaw.xtext.xaw.impl.TableRowLiteralImpl <em>Table Row Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see tablesaw.xtext.xaw.impl.TableRowLiteralImpl
     * @see tablesaw.xtext.xaw.impl.XawPackageImpl#getTableRowLiteral()
     * @generated
     */
    EClass TABLE_ROW_LITERAL = eINSTANCE.getTableRowLiteral();

    /**
     * The meta object literal for the '<em><b>Expressions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE_ROW_LITERAL__EXPRESSIONS = eINSTANCE.getTableRowLiteral_Expressions();

  }

} //XawPackage
