/**
 * generated by Xtext 2.12.0
 */
package tablesaw.xtext.validation;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.xbase.XExpression;
import tablesaw.xtext.validation.AbstractXawValidator;
import tablesaw.xtext.xaw.InlineTableRow;
import tablesaw.xtext.xaw.TableLiteral;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class XawValidator extends AbstractXawValidator {
  @Override
  protected boolean isValueExpectedRecursive(final XExpression expr) {
    boolean _xblockexpression = false;
    {
      final EObject parent = expr.eContainer();
      if (((parent instanceof InlineTableRow) || (parent.eContainer() instanceof TableLiteral))) {
        return true;
      }
      _xblockexpression = super.isValueExpectedRecursive(expr);
    }
    return _xblockexpression;
  }
}
