/*
 * generated by Xtext 2.12.0
 */
package tablesaw.xtext.validation

import org.eclipse.xtext.xbase.XExpression
import tablesaw.xtext.xaw.InlineTableRow
import tablesaw.xtext.xaw.TableLiteral

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class XawValidator extends AbstractXawValidator {

	override protected isValueExpectedRecursive(XExpression expr) {
		val parent = expr.eContainer
		if (parent instanceof InlineTableRow || parent.eContainer instanceof TableLiteral) {
			return true
		}
		super.isValueExpectedRecursive(expr)
	}
		
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					XawPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	
}
