/*
 * generated by Xtext 2.14.0
 */
package tablesaw.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import tablesaw.xtext.ui.internal.XtextActivator;

public class XawUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("tablesaw.xtext.Xaw");
	}

}
