/**
 * generated by Xtext 2.12.0
 */
package tablesaw.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import tablesaw.xtext.ui.AbstractXawUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class XawUiModule extends AbstractXawUiModule {
  public XawUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
